steps:
# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'dolittle-build-testing'
#     scannerMode: 'MSBuild'
#     projectKey: $(sonarProjectKey)
#     projectName: $(sonarProjectName)

- bash: dotnet --info
  displayName: Info

- bash: dotnet restore --no-cache --verbosity detailed --configuration Release
  displayName: Build

- bash: dotnet build --no-restore --verbosity detailed --configuration Release
  displayName: Build
  
- bash: dotnet test --verbosity detailed --configuration Release --no-build
  displayName: Test

- bash: dotnet pack --verbosity detailed --configuration Release --no-build --output "$(Agent.TempDirectory)/Artifacts" /p:PackageVersion=$(NewVersion.NextVersion) -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
  displayName: Pack

# - task: SonarCloudAnalyze@1
