steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "2.2.402"

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'dolittle-build-testing'
#     scannerMode: 'MSBuild'
#     projectKey: $(sonarProjectKey)
#     projectName: $(sonarProjectName)

- bash: dotnet build --configuration Release
  displayName: Build
  
- bash: dotnet test --no-build
  displayName: Test

- bash: dotnet pack --no-build --output "$(Agent.BuildDirectory)/Artifacts" /p:PackageVersion=$(NewVersion.NextVersion)
  displayName: Pack

# - task: SonarCloudAnalyze@1
