parameters:
  buildConfiguration: 'Release'
  CWD: $(System.DefaultWorkingDirectory)

steps:
- bash: dotnet restore --no-cache --configfile /root/.nuget/NuGet.Config
  workingDirectory: ${{ parameters.CWD }}
  displayName: Restore

- bash: dotnet build --no-restore --configuration ${{ parameters.buildConfiguration }}
  workingDirectory: ${{ parameters.CWD }}
  displayName: Build

- bash: dotnet test --no-build --configuration ${{ parameters.buildConfiguration }}
  workingDirectory: ${{ parameters.CWD }}    
  displayName: Test
