steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "2.2.402"

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'dolittle-build-testing'
#     scannerMode: 'MSBuild'
#     projectKey: $(sonarProjectKey)
#     projectName: $(sonarProjectName)

- bash: dotnet build --configuration Release
  displayName: Build
  
- bash: dotnet test --no-build --configuration Release
  displayName: Test

- bash: dotnet pack --no-restore --output $(sharedPackagesFolder) /p:PackageVersion=$(NewVersion.NextVersion)
  condition: and(succeeded(), eq(variables['Context.ShouldPublish'], 'true'))
  displayName: Pack
  condition: and(succeeded(), ne(variables['NewVersion.NextVersion'], ''))

# - task: SonarCloudAnalyze@1
