steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "2.2.402"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dolittle-build-testing'
    scannerMode: 'MSBuild'
    projectKey: $(sonarProjectKey)
    projectName: $(sonarProjectName)

- bash: dotnet build --configuration Release
  displayName: Build
  
- bash: dotnet test --no-build --configuration Release
  displayName: Test

- bash: dotnet pack --output /root/.nuget/dolittle-packages /p:PackageVersion=$(NewVersion.NextVersion)
  displayName: Pack
  condition: and(succeeded(), ne(variables['NewVersion.NextVersion'], ''))

- task: SonarCloudAnalyze@1
