steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: "2.2.402"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dolittle-build-testing'
    scannerMode: 'MSBuild'
    projectKey: $(sonarProjectKey)
    projectName: $(sonarProjectName)

- bash: dotnet build --configuration Release
  displayName: Build
  
- bash: dotnet test --no-build --configuration Release
  displayName: Test

- bash: dotnet pack --output /root/.nuget/dolittle-packages /p:PackageVersion=$(NewVersion.NextVersion)
  displayName: Pack
  condition: and(succeeded(), ne(variables['NewVersion.NextVersion'], ''))

- task: NuGetCommand@2
  displayName: Push Nuget packs
  condition: and(succeeded(), eq(variables['Context.ShouldPublish'], 'true'))
  inputs:
    command: push
    nugetFeedType: "external"
    packagesToPush: "/root/.nuget/dolittle-packages/**/*.nupkg;!/root/.nuget/dolittle-packages/**/*.symbols.nupkg"
    publishFeedCredentials: "myget_mathieu"

- task: SonarCloudAnalyze@1
