parameters:
  buildConfiguration: 'Release'
  CWD: $(System.DefaultWorkingDirectory)

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dolittle-build-testing'
    scannerMode: 'MSBuild'
    projectKey: $(sonarProjectKey)
    projectName: $(sonarProjectName)
    
- bash: dotnet restore --no-cache --configfile /root/.nuget/NuGet.Config
  workingDirectory: ${{ parameters.CWD }}
  displayName: Restore

- bash: dotnet build --no-restore --configuration ${{ parameters.buildConfiguration }}
  workingDirectory: ${{ parameters.CWD }}
  displayName: Build
  
- task: SonarCloudAnalyze@1

- bash: dotnet test --no-build --configuration ${{ parameters.buildConfiguration }}
  workingDirectory: ${{ parameters.CWD }}    
  displayName: Test
